export const AUTH_REGISTERED = 'REGISTERED'
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE'
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR'

export const SESSION_SET_URL_ROOT = 'SESSION_SET_URL_ROOT'
export const SESSION_LOGOUT = 'SESSION_LOGOUT'
