export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE'
export const AUTH_START_WORK = 'AUTH_START_WORK'
export const AUTH_STOP_WORK = 'AUTH_STOP_WORK'

export const SESSION_SET_URL_ROOT = 'SESSION_SET_URL_ROOT'
export const SESSION_LOGIN = 'SESSION_LOGIN'
export const SESSION_LOGOUT = 'SESSION_LOGOUT'
export const SESSION_LOAD_STATE_FROM_STORAGE = 'SESSION_LOAD_STATE_FROM_STORAGE'

export const MSG_INFO = 'MSG_INFO'
export const MSG_ERROR = 'MSG_ERROR'
export const MSG_CLEAR = 'MSG_CLEAR'

export const USER_LOAD_INFO = 'USER_LOAD_INFO'

export const TEAM_LOAD_INFO = 'TEAM_LOAD_INFO'
